### ISSUE TITLE
Revisar o Escopo.

### ISSUE THREAD

**Issue by eliseukadesh67** [fga-eps-mds/2019.2-Chatbot-Nilo#30]
## Descrição

O Escopo atual está nebuloso, e provavelmente muito grande para o prazo da Release 2.
Então o escopo deve ser re-avaliado junto ao Product Owner. 

Tasks(Tarefas)

- [x] Revisar o Escopo.
- [x] Redefinir o Documento de Escopo.

## Critérios de Aceitação

- [x] Cumprir as tarefas previstas anteriormente.

PS: Caso o Escopo seja re-definido, o Roadmap e o Backlog estarão sujeitos a alterações.

**Comment by httpaiva** [comment]
Numa reunião com o monitor da disciplina de MDS hoje, foi-nos aconselhado que resumíssemos o escopo para focar somente no estágio.
