### ISSUE TITLE
Retirar teste de style do gitlab-ci

### ISSUE THREAD

**Issue by yukioz** [fga-eps-mds/2019.2-Chatbot-Nilo#59]
## Descrição

problemas com o "- flake8 --exclude venv" alterações no código estão sendo prejudicadas constantemente, por conta disso foi retirado do código.

Olhar  nos logs dos commit os erros e como consertá-los pode ser acessando a os logs do commit no git lab 
![image](https://user-images.githubusercontent.com/43673797/68171581-18813480-ff53-11e9-95e0-54d863745458.png)

Para entrar nos logs devemos, entrar nos commits, clickar nos pequeno x e ir nos detalhes. Logo em seguida iremos ao test style e estaremos nos logs do CI.

**Comment by eliseukadesh67** [comment]
Os testes do Gitlab-CI continuam acusando erros nos commits, sendo que na maioria são apenas espaços vazios, ou identações diferentes.

**Comment by eliseukadesh67** [comment]
Hoje ás 23:21, solicitei ao monitor da disciplina do projeto, que nos auxiliasse com o CI do nosso projeto, ja que anteriormente ele havia sugerido um tutorial basico de DevOps e CI que seria ministrado por um colega do nosso monitor.
